services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    command: bash -c 'rm -f /tmp/server.pid && bundle exec rails s -b 0.0.0.0 -P /tmp/server.pid'
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    links:
      - db
      - redis
    environment:
      REDIS_URL: redis://redis:6379
  db:
    image: postgres:14.3
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-db:/var/lib/postgresql/data
  job:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bundle exec sidekiq
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    depends_on:
      - db
      - redis
    environment:
      REDIS_URL: redis://redis:6379
  redis:
    image: redis
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis:/var/lib/redis/data
volumes:
  bundle:
  postgres-db:
  redis:
