default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: moneydb_development 
  username: postgres
  password: password
  host: db
  port: 5432
  min_messages: warning

test:
  <<: *default
  database: moneydb_test
  username: postgres
  password: password
  host: db
  port: 5432

production:
  <<: *default
  database: moneydb
  username: postgres
  password: <%= ENV["MONEY_DATABASE_PASSWORD"] %>
